@startuml
'https://plantuml.com/use-case-diagram

:Main Admin: as Admin
(Use the application) as (Use)

User -> (Start)
User --> (Use)

Admin ---> (Use)

note right of Admin : This is an example.

note right of (Use)
A note can also
be on several lines
end note

note "This note is connected\nto several objects." as N2
(Start) .. N2
N2 .. (Use)
OW - UC1
UC1 ..> UC1.1 : optional
    UC1.1 ..>UCa : include
UC1 ..> UC1.2 : optional
    UC1.2 --> UCa : include
UC1 ..> UC1.3 : optional
    UC1.3 --> UCa : include
UC1 - worldDatabase
@enduml