@startuml
actor AL as "Demographer"

rectangle worldDatabase

rectangle "World Population Data System" {
	usecase UC7 as "Fetch Population"
	usecase UC7.1 as "Chinese"
	usecase UC7.2 as "English"
	usecase UC7.3 as "Hindi"
	usecase UC7.4 as "Spanish"
	usecase UC7.5 as "Arabic"

	usecase UCa as "Display Population by Language"


AL - UC7
UC7 ..> UC7.1 : optional
    UC7.1 --> UCa : include
UC7 ..> UC7.2 : optional
    UC7.2 --> UCa : include
UC7 ..> UC7.3 : optional
    UC7.3 --> UCa : include
UC7 ..> UC7.4 : optional
    UC7.4 --> UCa : include
UC7 ..> UC7.5 : optional
    UC7.5 --> UCa : include

UC7 - worldDatabase
@enduml