@startuml

actor DM as "Demographer"

rectangle WorldDatabase

rectangle "Population" {
    usecase UC4 as "
    by role"

    usecase UCa as "Print population"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml